version: '3.1'

services:
  routinder-dev-db:
    # platform: linux/x86_64
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      TZ: Asia/Seoul
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
